/**
 * Generates src/data/posts.data.ts from Markdown files in content/posts/
 *
 * Run: node scripts/generate-posts.js
 * Or: npm run generate-posts
 *
 * Each .md file in content/posts/ must have frontmatter:
 * ---
 * slug: my-post-slug
 * title: My Post Title
 * excerpt: Short description
 * date: YYYY-MM-DD
 * ---
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const POSTS_DIR = path.join(ROOT, "content", "posts");
const OUTPUT_FILE = path.join(ROOT, "src", "data", "posts.data.ts");

const requiredFields = ["slug", "title", "excerpt", "date"];

function escapeForTs(str) {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

function generatePosts() {
  if (!fs.existsSync(POSTS_DIR)) {
    console.error(`Posts directory not found: ${POSTS_DIR}`);
    process.exit(1);
  }

  const files = fs
    .readdirSync(POSTS_DIR)
    .filter((f) => f.endsWith(".md") && f !== "README.md");
  const posts = [];

  for (const file of files) {
    const filePath = path.join(POSTS_DIR, file);
    const raw = fs.readFileSync(filePath, "utf-8");
    const { data, content } = matter(raw);

    for (const field of requiredFields) {
      if (data[field] == null || data[field] === "") {
        console.error(`Missing field "${field}" in ${file}`);
        process.exit(1);
      }
    }

    const dateStr =
      typeof data.date === "string"
        ? data.date
        : data.date instanceof Date
          ? data.date.toISOString().slice(0, 10)
          : String(data.date).slice(0, 10);

    posts.push({
      slug: data.slug,
      title: data.title,
      excerpt: data.excerpt,
      date: dateStr,
      content: content.trim(),
    });
  }

  posts.sort((a, b) => (b.date < a.date ? -1 : 1));

  const tsContent = `// Auto-generated by scripts/generate-posts.js — do not edit manually
import type { PostType } from "@/types/post.type";

export const postsData: readonly PostType[] = [
${posts
  .map(
    (p) => `  {
    slug: ${JSON.stringify(p.slug)},
    title: ${JSON.stringify(p.title)},
    excerpt: ${JSON.stringify(p.excerpt)},
    date: ${JSON.stringify(p.date)},
    content: \`${escapeForTs(p.content)}\`,
  }`
  )
  .join(",\n")}
] as const;

export function getPostBySlug(slug: string): PostType | undefined {
  return postsData.find((post) => post.slug === slug);
}
`;

  fs.writeFileSync(OUTPUT_FILE, tsContent, "utf-8");
  console.log(`Generated ${posts.length} posts → ${OUTPUT_FILE}`);
}

generatePosts();
